#include "review_ui.h"

#include <cstdio>
#include <cstdint>
#include <cstring>

// Generated by tools/buildfont.sh from the deck's glyph set. These are the
// fallback used whenever a runtime font (pushed to /data/fonts/, see
// docs/sync-protocol.md) hasn't been loaded for a given size.
LV_FONT_DECLARE(font_cjk_48);
LV_FONT_DECLARE(font_cjk_28);
LV_FONT_DECLARE(font_cjk_20);
LV_FONT_DECLARE(font_cjk_16);

namespace ui {
namespace {

// Anki's queue colours, which are worth keeping: they are already in the
// user's head from the desktop app.
// lv_color_hex is a runtime function, so these cannot be constexpr.
inline lv_color_t kBlue() { return lv_color_hex(0x3B82F6); }   // learning
inline lv_color_t kGreen() { return lv_color_hex(0x22C55E); }  // due
inline lv_color_t kAmber() { return lv_color_hex(0xF59E0B); }  // new
inline lv_color_t kBg() { return lv_color_hex(0x101014); }
inline lv_color_t kFg() { return lv_color_hex(0xF5F5F5); }
inline lv_color_t kMuted() { return lv_color_hex(0x9CA3AF); }

struct Widgets {
  lv_obj_t* root = nullptr;
  lv_obj_t* topbar = nullptr;
  lv_obj_t* back_btn = nullptr;
  lv_obj_t* deck_label = nullptr;
  lv_obj_t* count_learning = nullptr;
  lv_obj_t* count_due = nullptr;
  lv_obj_t* count_fresh = nullptr;
  lv_obj_t* battery = nullptr;

  lv_obj_t* body = nullptr;
  lv_obj_t* front = nullptr;
  lv_obj_t* reading = nullptr;
  lv_obj_t* divider = nullptr;
  lv_obj_t* back = nullptr;
  lv_obj_t* hint = nullptr;

  lv_obj_t* buttons = nullptr;
  lv_obj_t* grade[4] = {nullptr, nullptr, nullptr, nullptr};
  lv_obj_t* grade_ivl[4] = {nullptr, nullptr, nullptr, nullptr};

  int w = 0;
  int h = 0;
  int body_h = 0;

  // Runtime fonts (see set_fonts()) override these when non-null; otherwise
  // the compiled-in subset above is used. Kept as pointers rather than
  // re-declaring the extern fonts everywhere they're used.
  const lv_font_t* font48 = &font_cjk_48;
  const lv_font_t* font28 = &font_cjk_28;
  const lv_font_t* font20 = &font_cjk_20;
  const lv_font_t* font16 = &font_cjk_16;

  // Pinyin tone-colouring gate (docs/sync-protocol.md): on for "zh" (the
  // default), off for every other lang.
  bool tone_color = true;

  RevealCallback on_reveal = nullptr;
  GradeCallback on_grade = nullptr;
  BackCallback on_back = nullptr;
};

Widgets g;

// ---------------------------------------------------------------------------
// Pinyin tone colouring.
//
// Anki-adjacent tone-colour schemes colour each syllable by its tone number;
// doing that properly needs a pinyin syllable dictionary, which is more
// machinery than this UI has any other reason to carry. The approximation
// used here needs none: pinyin's tone mark always sits on a syllable's one
// vowel, so scanning for tone-marked vowels and colouring from wherever the
// previous marked vowel (or the start of the string) left off is exactly a
// syllable's leading consonant(s) plus its vowel -- and any consonants
// trailing the very last marked vowel (e.g. the "n" in "kan4") correctly
// share its colour too, since there is nothing after them to hand off to.
// The one case this doesn't reconstruct correctly is a fully toneless
// (neutral) syllable with no diacritic at all sitting between two marked
// ones -- it gets absorbed into whichever neighbour's scan reaches it first
// (the preceding one, here) rather than getting its own neutral colour. That
// is a deliberate simplification, not a bug: neutral tone is already the
// "no information" case, so folding it into an adjacent colour is a minor
// cosmetic miss, not a wrong reading.
struct ToneVowel {
  uint8_t b0, b1;  // UTF-8 bytes of the toned vowel (all are 2-byte in this range)
  int tone;
};
// clang-format off
constexpr ToneVowel kToneVowels[] = {
  {0xC4, 0x81, 1}, {0xC3, 0xA1, 2}, {0xC7, 0x8E, 3}, {0xC3, 0xA0, 4},  // a: ā á ǎ à
  {0xC4, 0x93, 1}, {0xC3, 0xA9, 2}, {0xC4, 0x9B, 3}, {0xC3, 0xA8, 4},  // e: ē é ě è
  {0xC4, 0xAB, 1}, {0xC3, 0xAD, 2}, {0xC7, 0x90, 3}, {0xC3, 0xAC, 4},  // i: ī í ǐ ì
  {0xC5, 0x8D, 1}, {0xC3, 0xB3, 2}, {0xC7, 0x92, 3}, {0xC3, 0xB2, 4},  // o: ō ó ǒ ò
  {0xC5, 0xAB, 1}, {0xC3, 0xBA, 2}, {0xC7, 0x94, 3}, {0xC3, 0xB9, 4},  // u: ū ú ǔ ù
  {0xC7, 0x96, 1}, {0xC7, 0x98, 2}, {0xC7, 0x9A, 3}, {0xC7, 0x9C, 4},  // ü: ǖ ǘ ǚ ǜ
};
// clang-format on

int tone_at(const char* s, size_t i, size_t len) {
  if (i + 1 >= len) return 0;
  const uint8_t b0 = static_cast<uint8_t>(s[i]);
  const uint8_t b1 = static_cast<uint8_t>(s[i + 1]);
  for (const auto& tv : kToneVowels) {
    if (tv.b0 == b0 && tv.b1 == b1) return tv.tone;
  }
  return 0;
}

lv_color_t tone_color(int tone) {
  switch (tone) {
    case 1: return lv_color_hex(0xEF4444);  // red, matches the Again button
    case 2: return lv_color_hex(0xF59E0B);  // amber, matches Hard
    case 3: return lv_color_hex(0x22C55E);  // green, matches Good
    case 4: return lv_color_hex(0x60A5FA);  // blue, matches Easy
    default: return lv_color_hex(0x9CA3AF);  // untoned run: neutral grey
  }
}

// A colored run within a pinyin reading: [text, text+len) rendered in one
// colour. LVGL v9 dropped the label widget's old `#RRGGBB text#` recolor
// markup in favour of lv_span (a heavier widget meant for rich text), so
// per-syllable colouring here is done the plain way instead: split the
// reading into runs and render each run as its own child label in a
// horizontal flex row (see the "reading" container built in init()).
struct ToneRun {
  const char* text;
  size_t len;
  int tone;  // 0 = untoned run, see tone_color()
};

// Splits `reading` into runs using the scheme described above `kToneVowels`.
// Returns the number of runs written to `out` (capped at `max_runs`).
//
// A syllable's coda (the letters after its tone-marked vowel, e.g. the "o"
// in "mao" or the "ng" in "xiang") is not itself tone-marked, so once the
// vowel is consumed the scan would otherwise hand those trailing letters to
// *whichever* tone mark it finds next -- the following syllable's, which is
// simply wrong, not just approximate. There is one place this can be fixed
// for free without a syllable dictionary: at the very end of the string,
// there is no following syllable to (mis)attribute a coda to, so any
// trailing untoned letters are merged into the last run instead of becoming
// their own grey segment. Mid-string codas keep landing on the next
// syllable's tone; that residual misattribution is the one documented
// simplification here (see the file comment above `kToneVowels`).
int split_pinyin_tones(const char* reading, ToneRun* out, int max_runs) {
  const size_t len = std::strlen(reading);
  int n = 0;
  size_t seg_start = 0;
  size_t i = 0;
  while (i < len) {
    const int tone = tone_at(reading, i, len);
    if (tone != 0) {
      if (n < max_runs) out[n++] = {reading + seg_start, i + 2 - seg_start, tone};
      seg_start = i + 2;
      i += 2;
    } else {
      ++i;
    }
  }
  if (seg_start < len) {
    if (n > 0) {
      out[n - 1].len += len - seg_start;  // trailing coda: extend the last syllable's run
    } else if (max_runs > 0) {
      out[n++] = {reading, len, 0};  // no tone marks anywhere: one neutral run
    }
  }
  return n;
}

// Picks the largest font from `fonts` (ordered largest first) whose rendered
// height fits `max_h`. Glosses vary wildly in length — "eight" versus "then;
// at once; just; only; with regard to" — and a fixed size either wastes the
// panel or silently clips the end of a definition, which is the worst
// outcome on a flashcard.
void fit_font(lv_obj_t* label, const lv_font_t* const* fonts, int n, int max_h) {
  for (int i = 0; i < n; ++i) {
    lv_obj_set_style_text_font(label, fonts[i], LV_PART_MAIN);
    lv_obj_update_layout(label);
    if (lv_obj_get_height(label) <= max_h) return;
  }
  // Nothing fit; the smallest is already applied.
}

lv_obj_t* make_label(lv_obj_t* parent, const lv_font_t* font, lv_color_t colour) {
  lv_obj_t* l = lv_label_create(parent);
  lv_obj_set_style_text_font(l, font, LV_PART_MAIN);
  lv_obj_set_style_text_color(l, colour, LV_PART_MAIN);
  lv_label_set_text(l, "");
  return l;
}

// One grading button: a coloured chip with the label above the interval.
lv_obj_t* make_grade_button(lv_obj_t* parent, const char* text, lv_color_t colour,
                            int index, int width) {
  lv_obj_t* btn = lv_obj_create(parent);
  lv_obj_set_size(btn, width, 46);
  lv_obj_set_style_bg_color(btn, colour, LV_PART_MAIN);
  lv_obj_set_style_bg_opa(btn, LV_OPA_COVER, LV_PART_MAIN);
  lv_obj_set_style_radius(btn, 6, LV_PART_MAIN);
  lv_obj_set_style_border_width(btn, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(btn, 2, LV_PART_MAIN);
  lv_obj_clear_flag(btn, LV_OBJ_FLAG_SCROLLABLE);

  lv_obj_t* name = lv_label_create(btn);
  lv_obj_set_style_text_font(name, &lv_font_montserrat_14, LV_PART_MAIN);
  lv_obj_set_style_text_color(name, lv_color_hex(0x0B0B0F), LV_PART_MAIN);
  lv_label_set_text(name, text);
  lv_obj_align(name, LV_ALIGN_TOP_MID, 0, 2);

  lv_obj_t* ivl = lv_label_create(btn);
  lv_obj_set_style_text_font(ivl, &lv_font_montserrat_14, LV_PART_MAIN);
  lv_obj_set_style_text_color(ivl, lv_color_hex(0x1F2937), LV_PART_MAIN);
  lv_label_set_text(ivl, "");
  lv_obj_align(ivl, LV_ALIGN_BOTTOM_MID, 0, -2);
  g.grade_ivl[index] = ivl;

  return btn;
}

}  // namespace

void init(int hor_res, int ver_res) {
  g.w = hor_res;
  g.h = ver_res;

  // A dedicated screen object, not lv_screen_active(): the home screen (see
  // home_ui.h) needs its own screen too, and main.cpp switches between the
  // two with lv_screen_load(). Building here rather than on whatever screen
  // happens to be active keeps this correct regardless of init order.
  lv_obj_t* scr = lv_obj_create(nullptr);
  g.root = scr;
  lv_obj_set_style_bg_color(scr, kBg(), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, LV_PART_MAIN);
  lv_obj_set_style_pad_all(scr, 0, LV_PART_MAIN);

  // --- top bar ------------------------------------------------------------
  g.topbar = lv_obj_create(scr);
  lv_obj_set_size(g.topbar, hor_res, 26);
  lv_obj_align(g.topbar, LV_ALIGN_TOP_MID, 0, 0);
  lv_obj_set_style_bg_color(g.topbar, lv_color_hex(0x18181D), LV_PART_MAIN);
  lv_obj_set_style_border_width(g.topbar, 0, LV_PART_MAIN);
  lv_obj_set_style_radius(g.topbar, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(g.topbar, 0, LV_PART_MAIN);
  lv_obj_clear_flag(g.topbar, LV_OBJ_FLAG_SCROLLABLE);

  // Small "<-" back target, left of the deck name. Touch-only on purpose:
  // the physical buttons keep exactly their existing review-loop meaning
  // (see set_back_callback()'s doc comment).
  g.back_btn = lv_label_create(g.topbar);
  lv_obj_set_style_text_font(g.back_btn, &lv_font_montserrat_14, LV_PART_MAIN);
  lv_obj_set_style_text_color(g.back_btn, kMuted(), LV_PART_MAIN);
  lv_label_set_text(g.back_btn, LV_SYMBOL_LEFT);
  lv_obj_align(g.back_btn, LV_ALIGN_LEFT_MID, 6, 0);
  lv_obj_add_flag(g.back_btn, LV_OBJ_FLAG_CLICKABLE);
  // A bit of padding around the glyph so it's a comfortable tap target
  // rather than exactly the glyph's own tiny bounding box.
  lv_obj_set_ext_click_area(g.back_btn, 10);
  lv_obj_add_event_cb(
      g.back_btn, [](lv_event_t*) { if (g.on_back) g.on_back(); }, LV_EVENT_CLICKED, nullptr);

  // The deck-subset font, not Montserrat: deck names carry deck-language
  // glyphs (the ç in "Français") that Montserrat's ASCII set cannot draw.
  g.deck_label = make_label(g.topbar, g.font16, kMuted());
  lv_obj_align(g.deck_label, LV_ALIGN_LEFT_MID, 22, 0);

  // Counts are right-aligned and colour-coded, matching Anki.
  g.count_fresh = make_label(g.topbar, &lv_font_montserrat_14, kAmber());
  lv_obj_align(g.count_fresh, LV_ALIGN_RIGHT_MID, -6, 0);
  g.count_due = make_label(g.topbar, &lv_font_montserrat_14, kGreen());
  lv_obj_align(g.count_due, LV_ALIGN_RIGHT_MID, -34, 0);
  g.count_learning = make_label(g.topbar, &lv_font_montserrat_14, kBlue());
  lv_obj_align(g.count_learning, LV_ALIGN_RIGHT_MID, -62, 0);

  g.battery = make_label(g.topbar, &lv_font_montserrat_14, kMuted());
  lv_obj_align(g.battery, LV_ALIGN_LEFT_MID, 0, 0);
  lv_obj_add_flag(g.battery, LV_OBJ_FLAG_HIDDEN);

  // --- body ---------------------------------------------------------------
  const int body_top = 26;
  const int body_h = ver_res - body_top - 56;
  g.body_h = body_h;
  g.body = lv_obj_create(scr);
  lv_obj_set_size(g.body, hor_res, body_h);
  lv_obj_align(g.body, LV_ALIGN_TOP_MID, 0, body_top);
  lv_obj_set_style_bg_opa(g.body, LV_OPA_TRANSP, LV_PART_MAIN);
  lv_obj_set_style_border_width(g.body, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(g.body, 6, LV_PART_MAIN);
  lv_obj_clear_flag(g.body, LV_OBJ_FLAG_SCROLLABLE);

  // The headword is the whole point of the screen, so it gets the big font
  // and the visual centre.
  g.front = make_label(g.body, g.font48, kFg());
  lv_label_set_long_mode(g.front, LV_LABEL_LONG_WRAP);
  lv_obj_set_width(g.front, hor_res - 16);
  lv_obj_set_style_text_align(g.front, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

  // A row rather than a single label: tone-coloured pinyin (see show_card())
  // is rendered as one child label per coloured run, since LVGL v9's label
  // widget has no built-in inline-colour markup.
  g.reading = lv_obj_create(g.body);
  lv_obj_set_width(g.reading, hor_res - 16);
  lv_obj_set_height(g.reading, LV_SIZE_CONTENT);
  lv_obj_set_style_bg_opa(g.reading, LV_OPA_TRANSP, LV_PART_MAIN);
  lv_obj_set_style_border_width(g.reading, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(g.reading, 0, LV_PART_MAIN);
  lv_obj_clear_flag(g.reading, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_flex_flow(g.reading, LV_FLEX_FLOW_ROW_WRAP);
  lv_obj_set_flex_align(g.reading, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                        LV_FLEX_ALIGN_CENTER);

  g.divider = lv_obj_create(g.body);
  lv_obj_set_size(g.divider, hor_res - 60, 1);
  lv_obj_set_style_bg_color(g.divider, lv_color_hex(0x33333A), LV_PART_MAIN);
  lv_obj_set_style_border_width(g.divider, 0, LV_PART_MAIN);
  lv_obj_set_style_radius(g.divider, 0, LV_PART_MAIN);

  g.back = make_label(g.body, g.font28, kFg());
  lv_label_set_long_mode(g.back, LV_LABEL_LONG_WRAP);
  lv_obj_set_width(g.back, hor_res - 16);
  lv_obj_set_style_text_align(g.back, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

  g.hint = make_label(g.body, &lv_font_montserrat_14, kMuted());
  lv_obj_set_width(g.hint, hor_res - 16);
  lv_obj_set_style_text_align(g.hint, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

  // --- grading buttons ----------------------------------------------------
  g.buttons = lv_obj_create(scr);
  lv_obj_set_size(g.buttons, hor_res, 56);
  lv_obj_align(g.buttons, LV_ALIGN_BOTTOM_MID, 0, 0);
  lv_obj_set_style_bg_opa(g.buttons, LV_OPA_TRANSP, LV_PART_MAIN);
  lv_obj_set_style_border_width(g.buttons, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(g.buttons, 4, LV_PART_MAIN);
  lv_obj_clear_flag(g.buttons, LV_OBJ_FLAG_SCROLLABLE);

  const int gap = 4;
  const int bw = (hor_res - 8 - gap * 3) / 4;
  const char* names[4] = {"Again", "Hard", "Good", "Easy"};
  const lv_color_t colours[4] = {lv_color_hex(0xEF4444), lv_color_hex(0xF59E0B),
                                 lv_color_hex(0x22C55E), lv_color_hex(0x60A5FA)};
  for (int i = 0; i < 4; ++i) {
    g.grade[i] = make_grade_button(g.buttons, names[i], colours[i], i, bw);
    lv_obj_align(g.grade[i], LV_ALIGN_LEFT_MID, i * (bw + gap), 0);
  }

  show_card({"", "", ""}, false);
  lv_screen_load(scr);
}

lv_obj_t* screen() { return g.root; }

void set_deck_name(const char* name) { lv_label_set_text(g.deck_label, name); }

void set_counts(const Counts& c) {
  lv_label_set_text_fmt(g.count_learning, "%d", c.learning);
  lv_label_set_text_fmt(g.count_due, "%d", c.due);
  lv_label_set_text_fmt(g.count_fresh, "%d", c.fresh);
}

void set_battery(int percent, bool charging) {
  lv_obj_clear_flag(g.battery, LV_OBJ_FLAG_HIDDEN);
  lv_label_set_text_fmt(g.battery, "%s%d%%", charging ? "+" : "", percent);
}

void set_back_callback(BackCallback on_back) { g.on_back = on_back; }

void set_lang(const char* lang) {
  g.tone_color = (lang == nullptr || lang[0] == '\0' || std::strcmp(lang, "zh") == 0);
}

void set_fonts(const lv_font_t* f48, const lv_font_t* f28, const lv_font_t* f20,
               const lv_font_t* f16) {
  if (f48) g.font48 = f48;
  if (f28) g.font28 = f28;
  if (f20) g.font20 = f20;
  if (f16) g.font16 = f16;
  // The card labels re-read these pointers on every show_card(), but the
  // topbar deck label is built once at init(). main.cpp now calls this
  // before init(), so the guard is what makes that ordering work; the
  // restyle covers a later call.
  if (g.deck_label) lv_obj_set_style_text_font(g.deck_label, g.font16, LV_PART_MAIN);
}

void show_card(const CardView& card, bool revealed) {
  lv_label_set_text(g.front, card.front);

  // Rebuild the reading row's children every card: the run count changes
  // with the text, so there's no fixed set of child labels to just re-text.
  lv_obj_clean(g.reading);
  const char* reading = card.reading ? card.reading : "";
  if (reading[0]) {
    if (g.tone_color) {
      ToneRun runs[24];
      const int n = split_pinyin_tones(reading, runs, 24);
      char buf[64];
      for (int i = 0; i < n; ++i) {
        const size_t len = runs[i].len < sizeof(buf) - 1 ? runs[i].len : sizeof(buf) - 1;
        std::memcpy(buf, runs[i].text, len);
        buf[len] = '\0';
        lv_obj_t* seg = make_label(g.reading, g.font28, tone_color(runs[i].tone));
        lv_label_set_text(seg, buf);
      }
    } else {
      // Non-Chinese decks: one neutral colour, no per-syllable split (see
      // set_lang()).
      lv_obj_t* seg = make_label(g.reading, g.font28, kBlue());
      lv_label_set_text(seg, reading);
    }
  }

  lv_label_set_text(g.back, card.back ? card.back : "");

  // The headword shrinks only if it is genuinely long; most are one or two
  // characters and should stay at the display size. fit_font always starts
  // its search from the largest font, so this is correct regardless of what
  // font the label was left in by a previous card or state. Built fresh each
  // call (not static) since set_fonts() can swap these pointers at runtime.
  const lv_font_t* const head_fonts[] = {g.font48, g.font28};

  if (revealed) {
    lv_obj_clear_flag(g.reading, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(g.divider, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(g.back, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(g.buttons, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(g.hint, LV_OBJ_FLAG_HIDDEN);

    fit_font(g.front, head_fonts, 2, g.body_h / 2);

    // Headword sits high, answer fills the space below it.
    lv_obj_align(g.front, LV_ALIGN_TOP_MID, 0, 6);
    lv_obj_align_to(g.reading, g.front, LV_ALIGN_OUT_BOTTOM_MID, 0, 8);
    lv_obj_align_to(g.divider, g.reading, LV_ALIGN_OUT_BOTTOM_MID, 0, 8);

    // Give the gloss whatever vertical space is actually left, then pick the
    // largest font that fits it.
    lv_obj_update_layout(g.body);
    const int used = lv_obj_get_y(g.divider) + 1 + 8;
    const int remaining = g.body_h - used - 8;
    const lv_font_t* const gloss_fonts[] = {g.font28, g.font20, g.font16};
    fit_font(g.back, gloss_fonts, 3, remaining > 0 ? remaining : 16);
    lv_obj_align_to(g.back, g.divider, LV_ALIGN_OUT_BOTTOM_MID, 0, 8);
  } else {
    // Prompt state: nothing but the headword, so there is no accidental
    // hint to read. The grading buttons are hidden too, because grading
    // before recall is meaningless.
    lv_obj_add_flag(g.reading, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(g.divider, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(g.back, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(g.buttons, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(g.hint, LV_OBJ_FLAG_HIDDEN);

    // The prompt has the whole body to itself (no reading/divider/gloss
    // below it), minus room for the "tap to reveal" hint at the bottom.
    fit_font(g.front, head_fonts, 2, g.body_h - 40);
    lv_obj_align(g.front, LV_ALIGN_CENTER, 0, -10);
    lv_label_set_text(g.hint, "tap to reveal");
    lv_obj_align(g.hint, LV_ALIGN_BOTTOM_MID, 0, -6);
  }
}

void set_callbacks(RevealCallback on_reveal, GradeCallback on_grade) {
  g.on_reveal = on_reveal;
  g.on_grade = on_grade;

  // The whole body is the reveal target, so there is no small tap area to
  // aim at on a 2" panel.
  lv_obj_add_flag(g.body, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_add_flag(g.body, LV_OBJ_FLAG_EVENT_BUBBLE);
  lv_obj_add_event_cb(
      g.body,
      [](lv_event_t*) {
        if (g.on_reveal) g.on_reveal();
      },
      LV_EVENT_CLICKED, nullptr);

  for (int i = 0; i < 4; ++i) {
    lv_obj_add_flag(g.grade[i], LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(g.grade[i], LV_OBJ_FLAG_EVENT_BUBBLE);
    // The rating (1..4) travels as the user data pointer.
    lv_obj_add_event_cb(
        g.grade[i],
        [](lv_event_t* e) {
          const int rating =
              static_cast<int>(reinterpret_cast<intptr_t>(lv_event_get_user_data(e)));
          if (g.on_grade) g.on_grade(rating);
        },
        LV_EVENT_CLICKED, reinterpret_cast<void*>(static_cast<intptr_t>(i + 1)));
  }
}

void set_intervals(const Intervals& iv) {
  const char* vals[4] = {iv.again, iv.hard, iv.good, iv.easy};
  for (int i = 0; i < 4; ++i) {
    lv_label_set_text(g.grade_ivl[i], vals[i] ? vals[i] : "");
    lv_obj_align(g.grade_ivl[i], LV_ALIGN_BOTTOM_MID, 0, -2);
  }
}

void show_done(int reviewed_today) {
  lv_obj_add_flag(g.reading, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(g.divider, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(g.buttons, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(g.back, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(g.hint, LV_OBJ_FLAG_HIDDEN);

  // g.front and g.back are reused from the card states, where fit_font may
  // have left either of them on a smaller font (a long headword shrinks
  // front, a long gloss shrinks back). This screen's text is fixed and
  // short, so just pin both back to their intended sizes explicitly rather
  // than inheriting whatever the last card happened to leave behind.
  lv_obj_set_style_text_font(g.front, g.font48, LV_PART_MAIN);
  lv_obj_set_style_text_font(g.back, g.font28, LV_PART_MAIN);

  lv_label_set_text(g.front, "\xE2\x9C\x93");  // check mark
  lv_obj_align(g.front, LV_ALIGN_CENTER, 0, -30);
  lv_label_set_text(g.back, "All done");
  lv_obj_align_to(g.back, g.front, LV_ALIGN_OUT_BOTTOM_MID, 0, 14);
  lv_label_set_text_fmt(g.hint, "%d reviewed today", reviewed_today);
  lv_obj_align(g.hint, LV_ALIGN_BOTTOM_MID, 0, -6);
}

}  // namespace ui
