#include "review_ui.h"

#include <cstdio>
#include <cstdint>

// Generated by tools/buildfont.sh from the deck's glyph set.
LV_FONT_DECLARE(font_cjk_48);
LV_FONT_DECLARE(font_cjk_28);
LV_FONT_DECLARE(font_cjk_20);
LV_FONT_DECLARE(font_cjk_16);

namespace ui {
namespace {

// Anki's queue colours, which are worth keeping: they are already in the
// user's head from the desktop app.
// lv_color_hex is a runtime function, so these cannot be constexpr.
inline lv_color_t kBlue() { return lv_color_hex(0x3B82F6); }   // learning
inline lv_color_t kGreen() { return lv_color_hex(0x22C55E); }  // due
inline lv_color_t kAmber() { return lv_color_hex(0xF59E0B); }  // new
inline lv_color_t kBg() { return lv_color_hex(0x101014); }
inline lv_color_t kFg() { return lv_color_hex(0xF5F5F5); }
inline lv_color_t kMuted() { return lv_color_hex(0x9CA3AF); }

struct Widgets {
  lv_obj_t* root = nullptr;
  lv_obj_t* topbar = nullptr;
  lv_obj_t* deck_label = nullptr;
  lv_obj_t* count_learning = nullptr;
  lv_obj_t* count_due = nullptr;
  lv_obj_t* count_fresh = nullptr;
  lv_obj_t* battery = nullptr;

  lv_obj_t* body = nullptr;
  lv_obj_t* front = nullptr;
  lv_obj_t* reading = nullptr;
  lv_obj_t* divider = nullptr;
  lv_obj_t* back = nullptr;
  lv_obj_t* hint = nullptr;

  lv_obj_t* buttons = nullptr;
  lv_obj_t* grade[4] = {nullptr, nullptr, nullptr, nullptr};
  lv_obj_t* grade_ivl[4] = {nullptr, nullptr, nullptr, nullptr};

  int w = 0;
  int h = 0;
  int body_h = 0;

  RevealCallback on_reveal = nullptr;
  GradeCallback on_grade = nullptr;
};

Widgets g;

// Picks the largest font from `fonts` (ordered largest first) whose rendered
// height fits `max_h`. Glosses vary wildly in length — "eight" versus "then;
// at once; just; only; with regard to" — and a fixed size either wastes the
// panel or silently clips the end of a definition, which is the worst
// outcome on a flashcard.
void fit_font(lv_obj_t* label, const lv_font_t* const* fonts, int n, int max_h) {
  for (int i = 0; i < n; ++i) {
    lv_obj_set_style_text_font(label, fonts[i], LV_PART_MAIN);
    lv_obj_update_layout(label);
    if (lv_obj_get_height(label) <= max_h) return;
  }
  // Nothing fit; the smallest is already applied.
}

lv_obj_t* make_label(lv_obj_t* parent, const lv_font_t* font, lv_color_t colour) {
  lv_obj_t* l = lv_label_create(parent);
  lv_obj_set_style_text_font(l, font, LV_PART_MAIN);
  lv_obj_set_style_text_color(l, colour, LV_PART_MAIN);
  lv_label_set_text(l, "");
  return l;
}

// One grading button: a coloured chip with the label above the interval.
lv_obj_t* make_grade_button(lv_obj_t* parent, const char* text, lv_color_t colour,
                            int index, int width) {
  lv_obj_t* btn = lv_obj_create(parent);
  lv_obj_set_size(btn, width, 46);
  lv_obj_set_style_bg_color(btn, colour, LV_PART_MAIN);
  lv_obj_set_style_bg_opa(btn, LV_OPA_COVER, LV_PART_MAIN);
  lv_obj_set_style_radius(btn, 6, LV_PART_MAIN);
  lv_obj_set_style_border_width(btn, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(btn, 2, LV_PART_MAIN);
  lv_obj_clear_flag(btn, LV_OBJ_FLAG_SCROLLABLE);

  lv_obj_t* name = lv_label_create(btn);
  lv_obj_set_style_text_font(name, &lv_font_montserrat_14, LV_PART_MAIN);
  lv_obj_set_style_text_color(name, lv_color_hex(0x0B0B0F), LV_PART_MAIN);
  lv_label_set_text(name, text);
  lv_obj_align(name, LV_ALIGN_TOP_MID, 0, 2);

  lv_obj_t* ivl = lv_label_create(btn);
  lv_obj_set_style_text_font(ivl, &lv_font_montserrat_14, LV_PART_MAIN);
  lv_obj_set_style_text_color(ivl, lv_color_hex(0x1F2937), LV_PART_MAIN);
  lv_label_set_text(ivl, "");
  lv_obj_align(ivl, LV_ALIGN_BOTTOM_MID, 0, -2);
  g.grade_ivl[index] = ivl;

  return btn;
}

}  // namespace

void init(int hor_res, int ver_res) {
  g.w = hor_res;
  g.h = ver_res;

  lv_obj_t* scr = lv_screen_active();
  lv_obj_set_style_bg_color(scr, kBg(), LV_PART_MAIN);
  lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, LV_PART_MAIN);
  lv_obj_set_style_pad_all(scr, 0, LV_PART_MAIN);

  // --- top bar ------------------------------------------------------------
  g.topbar = lv_obj_create(scr);
  lv_obj_set_size(g.topbar, hor_res, 26);
  lv_obj_align(g.topbar, LV_ALIGN_TOP_MID, 0, 0);
  lv_obj_set_style_bg_color(g.topbar, lv_color_hex(0x18181D), LV_PART_MAIN);
  lv_obj_set_style_border_width(g.topbar, 0, LV_PART_MAIN);
  lv_obj_set_style_radius(g.topbar, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(g.topbar, 0, LV_PART_MAIN);
  lv_obj_clear_flag(g.topbar, LV_OBJ_FLAG_SCROLLABLE);

  g.deck_label = make_label(g.topbar, &lv_font_montserrat_14, kMuted());
  lv_obj_align(g.deck_label, LV_ALIGN_LEFT_MID, 6, 0);

  // Counts are right-aligned and colour-coded, matching Anki.
  g.count_fresh = make_label(g.topbar, &lv_font_montserrat_14, kAmber());
  lv_obj_align(g.count_fresh, LV_ALIGN_RIGHT_MID, -6, 0);
  g.count_due = make_label(g.topbar, &lv_font_montserrat_14, kGreen());
  lv_obj_align(g.count_due, LV_ALIGN_RIGHT_MID, -34, 0);
  g.count_learning = make_label(g.topbar, &lv_font_montserrat_14, kBlue());
  lv_obj_align(g.count_learning, LV_ALIGN_RIGHT_MID, -62, 0);

  g.battery = make_label(g.topbar, &lv_font_montserrat_14, kMuted());
  lv_obj_align(g.battery, LV_ALIGN_LEFT_MID, 0, 0);
  lv_obj_add_flag(g.battery, LV_OBJ_FLAG_HIDDEN);

  // --- body ---------------------------------------------------------------
  const int body_top = 26;
  const int body_h = ver_res - body_top - 56;
  g.body_h = body_h;
  g.body = lv_obj_create(scr);
  lv_obj_set_size(g.body, hor_res, body_h);
  lv_obj_align(g.body, LV_ALIGN_TOP_MID, 0, body_top);
  lv_obj_set_style_bg_opa(g.body, LV_OPA_TRANSP, LV_PART_MAIN);
  lv_obj_set_style_border_width(g.body, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(g.body, 6, LV_PART_MAIN);
  lv_obj_clear_flag(g.body, LV_OBJ_FLAG_SCROLLABLE);

  // The headword is the whole point of the screen, so it gets the big font
  // and the visual centre.
  g.front = make_label(g.body, &font_cjk_48, kFg());
  lv_label_set_long_mode(g.front, LV_LABEL_LONG_WRAP);
  lv_obj_set_width(g.front, hor_res - 16);
  lv_obj_set_style_text_align(g.front, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

  g.reading = make_label(g.body, &font_cjk_28, kBlue());
  lv_obj_set_width(g.reading, hor_res - 16);
  lv_obj_set_style_text_align(g.reading, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

  g.divider = lv_obj_create(g.body);
  lv_obj_set_size(g.divider, hor_res - 60, 1);
  lv_obj_set_style_bg_color(g.divider, lv_color_hex(0x33333A), LV_PART_MAIN);
  lv_obj_set_style_border_width(g.divider, 0, LV_PART_MAIN);
  lv_obj_set_style_radius(g.divider, 0, LV_PART_MAIN);

  g.back = make_label(g.body, &font_cjk_28, kFg());
  lv_label_set_long_mode(g.back, LV_LABEL_LONG_WRAP);
  lv_obj_set_width(g.back, hor_res - 16);
  lv_obj_set_style_text_align(g.back, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

  g.hint = make_label(g.body, &lv_font_montserrat_14, kMuted());
  lv_obj_set_width(g.hint, hor_res - 16);
  lv_obj_set_style_text_align(g.hint, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);

  // --- grading buttons ----------------------------------------------------
  g.buttons = lv_obj_create(scr);
  lv_obj_set_size(g.buttons, hor_res, 56);
  lv_obj_align(g.buttons, LV_ALIGN_BOTTOM_MID, 0, 0);
  lv_obj_set_style_bg_opa(g.buttons, LV_OPA_TRANSP, LV_PART_MAIN);
  lv_obj_set_style_border_width(g.buttons, 0, LV_PART_MAIN);
  lv_obj_set_style_pad_all(g.buttons, 4, LV_PART_MAIN);
  lv_obj_clear_flag(g.buttons, LV_OBJ_FLAG_SCROLLABLE);

  const int gap = 4;
  const int bw = (hor_res - 8 - gap * 3) / 4;
  const char* names[4] = {"Again", "Hard", "Good", "Easy"};
  const lv_color_t colours[4] = {lv_color_hex(0xEF4444), lv_color_hex(0xF59E0B),
                                 lv_color_hex(0x22C55E), lv_color_hex(0x60A5FA)};
  for (int i = 0; i < 4; ++i) {
    g.grade[i] = make_grade_button(g.buttons, names[i], colours[i], i, bw);
    lv_obj_align(g.grade[i], LV_ALIGN_LEFT_MID, i * (bw + gap), 0);
  }

  show_card({"", "", ""}, false);
}

void set_deck_name(const char* name) { lv_label_set_text(g.deck_label, name); }

void set_counts(const Counts& c) {
  lv_label_set_text_fmt(g.count_learning, "%d", c.learning);
  lv_label_set_text_fmt(g.count_due, "%d", c.due);
  lv_label_set_text_fmt(g.count_fresh, "%d", c.fresh);
}

void set_battery(int percent, bool charging) {
  lv_obj_clear_flag(g.battery, LV_OBJ_FLAG_HIDDEN);
  lv_label_set_text_fmt(g.battery, "%s%d%%", charging ? "+" : "", percent);
}

void show_card(const CardView& card, bool revealed) {
  lv_label_set_text(g.front, card.front);
  lv_label_set_text(g.reading, card.reading ? card.reading : "");
  lv_label_set_text(g.back, card.back ? card.back : "");

  // The headword shrinks only if it is genuinely long; most are one or two
  // characters and should stay at the display size. fit_font always starts
  // its search from the largest font, so this is correct regardless of what
  // font the label was left in by a previous card or state.
  static const lv_font_t* const head_fonts[] = {&font_cjk_48, &font_cjk_28};

  if (revealed) {
    lv_obj_clear_flag(g.reading, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(g.divider, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(g.back, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(g.buttons, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(g.hint, LV_OBJ_FLAG_HIDDEN);

    fit_font(g.front, head_fonts, 2, g.body_h / 2);

    // Headword sits high, answer fills the space below it.
    lv_obj_align(g.front, LV_ALIGN_TOP_MID, 0, 6);
    lv_obj_align_to(g.reading, g.front, LV_ALIGN_OUT_BOTTOM_MID, 0, 8);
    lv_obj_align_to(g.divider, g.reading, LV_ALIGN_OUT_BOTTOM_MID, 0, 8);

    // Give the gloss whatever vertical space is actually left, then pick the
    // largest font that fits it.
    lv_obj_update_layout(g.body);
    const int used = lv_obj_get_y(g.divider) + 1 + 8;
    const int remaining = g.body_h - used - 8;
    static const lv_font_t* const gloss_fonts[] = {&font_cjk_28, &font_cjk_20,
                                                   &font_cjk_16};
    fit_font(g.back, gloss_fonts, 3, remaining > 0 ? remaining : 16);
    lv_obj_align_to(g.back, g.divider, LV_ALIGN_OUT_BOTTOM_MID, 0, 8);
  } else {
    // Prompt state: nothing but the headword, so there is no accidental
    // hint to read. The grading buttons are hidden too, because grading
    // before recall is meaningless.
    lv_obj_add_flag(g.reading, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(g.divider, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(g.back, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(g.buttons, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(g.hint, LV_OBJ_FLAG_HIDDEN);

    // The prompt has the whole body to itself (no reading/divider/gloss
    // below it), minus room for the "tap to reveal" hint at the bottom.
    fit_font(g.front, head_fonts, 2, g.body_h - 40);
    lv_obj_align(g.front, LV_ALIGN_CENTER, 0, -10);
    lv_label_set_text(g.hint, "tap to reveal");
    lv_obj_align(g.hint, LV_ALIGN_BOTTOM_MID, 0, -6);
  }
}

void set_callbacks(RevealCallback on_reveal, GradeCallback on_grade) {
  g.on_reveal = on_reveal;
  g.on_grade = on_grade;

  // The whole body is the reveal target, so there is no small tap area to
  // aim at on a 2" panel.
  lv_obj_add_flag(g.body, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_add_flag(g.body, LV_OBJ_FLAG_EVENT_BUBBLE);
  lv_obj_add_event_cb(
      g.body,
      [](lv_event_t*) {
        if (g.on_reveal) g.on_reveal();
      },
      LV_EVENT_CLICKED, nullptr);

  for (int i = 0; i < 4; ++i) {
    lv_obj_add_flag(g.grade[i], LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(g.grade[i], LV_OBJ_FLAG_EVENT_BUBBLE);
    // The rating (1..4) travels as the user data pointer.
    lv_obj_add_event_cb(
        g.grade[i],
        [](lv_event_t* e) {
          const int rating =
              static_cast<int>(reinterpret_cast<intptr_t>(lv_event_get_user_data(e)));
          if (g.on_grade) g.on_grade(rating);
        },
        LV_EVENT_CLICKED, reinterpret_cast<void*>(static_cast<intptr_t>(i + 1)));
  }
}

void set_intervals(const Intervals& iv) {
  const char* vals[4] = {iv.again, iv.hard, iv.good, iv.easy};
  for (int i = 0; i < 4; ++i) {
    lv_label_set_text(g.grade_ivl[i], vals[i] ? vals[i] : "");
    lv_obj_align(g.grade_ivl[i], LV_ALIGN_BOTTOM_MID, 0, -2);
  }
}

void show_done(int reviewed_today) {
  lv_obj_add_flag(g.reading, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(g.divider, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_flag(g.buttons, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(g.back, LV_OBJ_FLAG_HIDDEN);
  lv_obj_clear_flag(g.hint, LV_OBJ_FLAG_HIDDEN);

  // g.front and g.back are reused from the card states, where fit_font may
  // have left either of them on a smaller font (a long headword shrinks
  // front, a long gloss shrinks back). This screen's text is fixed and
  // short, so just pin both back to their intended sizes explicitly rather
  // than inheriting whatever the last card happened to leave behind.
  lv_obj_set_style_text_font(g.front, &font_cjk_48, LV_PART_MAIN);
  lv_obj_set_style_text_font(g.back, &font_cjk_28, LV_PART_MAIN);

  lv_label_set_text(g.front, "\xE2\x9C\x93");  // check mark
  lv_obj_align(g.front, LV_ALIGN_CENTER, 0, -30);
  lv_label_set_text(g.back, "All done");
  lv_obj_align_to(g.back, g.front, LV_ALIGN_OUT_BOTTOM_MID, 0, 14);
  lv_label_set_text_fmt(g.hint, "%d reviewed today", reviewed_today);
  lv_obj_align(g.hint, LV_ALIGN_BOTTOM_MID, 0, -6);
}

}  // namespace ui
